/*
 * This file was automatically generated by EvoSuite
 */

package geo.google.mapping;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import geo.google.mapping.XmlToUsAddressFunctor;

public class XmlToUsAddressFunctorEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 geo.google.mapping.XmlToUsAddressFunctor.getInstance()Lgeo/google/mapping/XmlToUsAddressFunctor;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      XmlToUsAddressFunctor xmlToUsAddressFunctor0 = XmlToUsAddressFunctor.getInstance();
      assertNotNull(xmlToUsAddressFunctor0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 geo.google.mapping.XmlToUsAddressFunctor.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      XmlToUsAddressFunctor xmlToUsAddressFunctor0 = new XmlToUsAddressFunctor();
      assertNotNull(xmlToUsAddressFunctor0);
  }
}
