/*
 * This file was automatically generated by EvoSuite
 */

package messages.session;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import client.ClientGameSession;
import java.util.HashMap;
import messages.session.SessionScoreMsg;

@RunWith(EvoSuiteRunner.class)
public class SessionScoreMsgEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 messages.session.SessionScoreMsg.execute(Lclient/ClientGameSession;)V: root-Branch
   * 2 messages.session.SessionScoreMsg.<init>(Ljava/util/HashMap;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      SessionScoreMsg sessionScoreMsg0 = new SessionScoreMsg(hashMap0);
      // Undeclared exception!
      try {
        sessionScoreMsg0.execute((ClientGameSession) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
