/*
 * This file was automatically generated by EvoSuite
 */

package com.allenstudio.ir.core.plugins;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.allenstudio.ir.core.plugins.CommonNoteModel;

public class CommonNoteModelEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 com.allenstudio.ir.core.plugins.CommonNoteModel.isSelected()Z: root-Branch
   * 2 com.allenstudio.ir.core.plugins.CommonNoteModel.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      CommonNoteModel commonNoteModel0 = new CommonNoteModel();
      boolean boolean0 = commonNoteModel0.isSelected();
      assertEquals(false, boolean0);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 com.allenstudio.ir.core.plugins.CommonNoteModel.setSelected(Z)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      CommonNoteModel commonNoteModel0 = new CommonNoteModel();
      commonNoteModel0.setSelected(false);
      assertEquals(false, commonNoteModel0.isSelected());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 com.allenstudio.ir.core.plugins.CommonNoteModel.getThumbnailContent()[Ljava/lang/String;: root-Branch
   * 2 com.allenstudio.ir.core.plugins.CommonNoteModel.<init>()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      CommonNoteModel commonNoteModel0 = new CommonNoteModel();
      String[] stringArray0 = commonNoteModel0.getThumbnailContent();
      assertNotNull(stringArray0);
  }
}
