/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.snippets;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.snippets.SnippetGetProcessList;

public class SnippetGetProcessListEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.core.snippets.SnippetGetProcessList.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      SnippetGetProcessList snippetGetProcessList0 = new SnippetGetProcessList();
      assertNotNull(snippetGetProcessList0);
  }
}
