/*
 * This file was automatically generated by EvoSuite
 */

package net.sourceforge.schemaspy.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import net.sourceforge.schemaspy.util.DbSpecificOption;

public class DbSpecificOptionEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   * 2 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DbSpecificOption dbSpecificOption0 = new DbSpecificOption((String) null, (String) null);
      assertEquals("DbSpecificOption name: 'null' value: 'null' description: 'null'", dbSpecificOption0.toString());
  }

  //Test case number: 1
  /*
   * 4 covered goals:
   * 1 net.sourceforge.schemaspy.util.DbSpecificOption.getName()Ljava/lang/String;: root-Branch
   * 2 net.sourceforge.schemaspy.util.DbSpecificOption.toString()Ljava/lang/String;: root-Branch
   * 3 net.sourceforge.schemaspy.util.DbSpecificOption.getDescription()Ljava/lang/String;: root-Branch
   * 4 net.sourceforge.schemaspy.util.DbSpecificOption.getValue()Ljava/lang/Object;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DbSpecificOption dbSpecificOption0 = new DbSpecificOption((String) null, (String) null, (String) null);
      String string0 = dbSpecificOption0.toString();
      assertEquals("DbSpecificOption name: 'null' value: 'null' description: 'null'", string0);
      assertNotNull(string0);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 net.sourceforge.schemaspy.util.DbSpecificOption.setValue(Ljava/lang/Object;)V: root-Branch
   * 2 net.sourceforge.schemaspy.util.DbSpecificOption.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      DbSpecificOption dbSpecificOption0 = new DbSpecificOption((String) null, (String) null, (String) null);
      dbSpecificOption0.setValue((Object) null);
      assertNull(dbSpecificOption0.getDescription());
  }
}
