/*
 * This file was automatically generated by EvoSuite
 */

package org.saxpath.helpers;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.saxpath.SAXPathException;
import org.saxpath.helpers.DefaultXPathHandler;

public class DefaultXPathHandlerEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endXPath()V: root-Branch
   * 2 org.saxpath.helpers.DefaultXPathHandler.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endXPath();
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startEqualityExpr()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startEqualityExpr();
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endRelativeLocationPath()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endRelativeLocationPath();
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endPathExpr()V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endPathExpr();
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endFilterExpr()V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endFilterExpr();
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endAdditiveExpr(I)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAdditiveExpr(865);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startOrExpr()V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startOrExpr();
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endAllNodeStep()V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAllNodeStep();
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startAndExpr()V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAndExpr();
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.variableReference(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test9()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.variableReference("]", "]");
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.literal(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.literal("");
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endRelationalExpr(I)V: root-Branch
   */
  @Test
  public void test11()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endRelationalExpr((-58));
  }

  //Test case number: 12
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startNameStep(ILjava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test12()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startNameStep((-281), "root case:", "root case:");
  }

  //Test case number: 13
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startFunction(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test13()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startFunction("", "");
  }

  //Test case number: 14
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endUnionExpr(Z)V: root-Branch
   */
  @Test
  public void test14()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endUnionExpr(false);
  }

  //Test case number: 15
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startFilterExpr()V: root-Branch
   */
  @Test
  public void test15()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startFilterExpr();
  }

  //Test case number: 16
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startTextNodeStep(I)V: root-Branch
   */
  @Test
  public void test16()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startTextNodeStep(0);
  }

  //Test case number: 17
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endMultiplicativeExpr(I)V: root-Branch
   */
  @Test
  public void test17()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endMultiplicativeExpr(0);
  }

  //Test case number: 18
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endProcessingInstructionNodeStep()V: root-Branch
   */
  @Test
  public void test18()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endProcessingInstructionNodeStep();
  }

  //Test case number: 19
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startRelationalExpr()V: root-Branch
   */
  @Test
  public void test19()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startRelationalExpr();
  }

  //Test case number: 20
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endOrExpr(Z)V: root-Branch
   */
  @Test
  public void test20()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endOrExpr(false);
  }

  //Test case number: 21
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endNameStep()V: root-Branch
   */
  @Test
  public void test21()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endNameStep();
  }

  //Test case number: 22
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startPredicate()V: root-Branch
   */
  @Test
  public void test22()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startPredicate();
  }

  //Test case number: 23
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endUnaryExpr(I)V: root-Branch
   */
  @Test
  public void test23()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endUnaryExpr(0);
  }

  //Test case number: 24
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endAbsoluteLocationPath()V: root-Branch
   */
  @Test
  public void test24()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAbsoluteLocationPath();
  }

  //Test case number: 25
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startXPath()V: root-Branch
   */
  @Test
  public void test25()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startXPath();
  }

  //Test case number: 26
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startCommentNodeStep(I)V: root-Branch
   */
  @Test
  public void test26()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startCommentNodeStep(0);
  }

  //Test case number: 27
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startAdditiveExpr()V: root-Branch
   */
  @Test
  public void test27()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAdditiveExpr();
  }

  //Test case number: 28
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startAbsoluteLocationPath()V: root-Branch
   */
  @Test
  public void test28()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAbsoluteLocationPath();
  }

  //Test case number: 29
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startMultiplicativeExpr()V: root-Branch
   */
  @Test
  public void test29()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startMultiplicativeExpr();
  }

  //Test case number: 30
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endTextNodeStep()V: root-Branch
   */
  @Test
  public void test30()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endTextNodeStep();
  }

  //Test case number: 31
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endCommentNodeStep()V: root-Branch
   */
  @Test
  public void test31()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endCommentNodeStep();
  }

  //Test case number: 32
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endAndExpr(Z)V: root-Branch
   */
  @Test
  public void test32()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAndExpr(false);
  }

  //Test case number: 33
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endFunction()V: root-Branch
   */
  @Test
  public void test33()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endFunction();
  }

  //Test case number: 34
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startUnaryExpr()V: root-Branch
   */
  @Test
  public void test34()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startUnaryExpr();
  }

  //Test case number: 35
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startPathExpr()V: root-Branch
   */
  @Test
  public void test35()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startPathExpr();
  }

  //Test case number: 36
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startProcessingInstructionNodeStep(ILjava/lang/String;)V: root-Branch
   */
  @Test
  public void test36()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startProcessingInstructionNodeStep((-187), "");
  }

  //Test case number: 37
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startUnionExpr()V: root-Branch
   */
  @Test
  public void test37()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startUnionExpr();
  }

  //Test case number: 38
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startAllNodeStep(I)V: root-Branch
   */
  @Test
  public void test38()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAllNodeStep(0);
  }

  //Test case number: 39
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endPredicate()V: root-Branch
   */
  @Test
  public void test39()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endPredicate();
  }

  //Test case number: 40
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.number(D)V: root-Branch
   */
  @Test
  public void test40()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.number(0.0);
  }

  //Test case number: 41
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.endEqualityExpr(I)V: root-Branch
   */
  @Test
  public void test41()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endEqualityExpr((-1));
  }

  //Test case number: 42
  /*
   * 1 covered goal:
   * 1 org.saxpath.helpers.DefaultXPathHandler.startRelativeLocationPath()V: root-Branch
   */
  @Test
  public void test42()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startRelativeLocationPath();
  }

  //Test case number: 43
  /*
   * 2 covered goals:
   * 1 org.saxpath.helpers.DefaultXPathHandler.number(I)V: root-Branch
   * 2 org.saxpath.helpers.DefaultXPathHandler.<init>()V: root-Branch
   */
  @Test
  public void test43()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.number(1);
  }
}
