/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.crypto.hash;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.crypto.hash.Sha256Hash;

public class Sha256HashEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Sha256Hash.<init>()V: root-Branch
   * 2 org.jsecurity.crypto.hash.Sha256Hash.fromBase64String(Ljava/lang/String;)Lorg/jsecurity/crypto/hash/Sha256Hash;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Sha256Hash sha256Hash0 = Sha256Hash.fromBase64String("~|");
      assertEquals("", sha256Hash0.toString());
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Sha256Hash.getAlgorithmName()Ljava/lang/String;: root-Branch
   * 2 org.jsecurity.crypto.hash.Sha256Hash.<init>(Ljava/lang/Object;Ljava/lang/Object;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Sha256Hash sha256Hash0 = new Sha256Hash((Object) "", (Object) "SHA-256");
      assertEquals("bbd07c4fc02c99b97124febf42c7b63b5011c0df28d409fbb486b5a9d2e615ea", sha256Hash0.toHex());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Sha256Hash.fromHexString(Ljava/lang/String;)Lorg/jsecurity/crypto/hash/Sha256Hash;: root-Branch
   * 2 org.jsecurity.crypto.hash.Sha256Hash.<init>()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        Sha256Hash.fromHexString("lqKW0iTyhcZ77pPDD4owkVfw2qNdxbh+QQt4YwoJz8c=");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Illegal hexadecimal charcter l at index 0
         */
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jsecurity.crypto.hash.Sha256Hash.<init>(Ljava/lang/Object;Ljava/lang/Object;I)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Sha256Hash sha256Hash0 = new Sha256Hash((Object) "\u0000", (Object) "\u0000", (int) (byte)0);
      assertEquals("96a296d224f285c67bee93c30f8a309157f0daa35dc5b87e410b78630a09cfc7", sha256Hash0.toString());
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Sha256Hash.<init>(Ljava/lang/Object;)V: root-Branch
   * 2 org.jsecurity.crypto.hash.Sha256Hash.getAlgorithmName()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Sha256Hash sha256Hash0 = new Sha256Hash((Object) "");
      assertEquals("SHA-256", sha256Hash0.getAlgorithmName());
  }
}
