/*
 * This file was automatically generated by EvoSuite
 */

package messages.global;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import messages.global.StopServerMsg;
import server.BomberServer;
import server.ClientInfo;

@RunWith(EvoSuiteRunner.class)
public class StopServerMsgEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 messages.global.StopServerMsg.execute(Lserver/BomberServer;Lserver/ClientInfo;)V: root-Branch
   * 2 messages.global.StopServerMsg.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      StopServerMsg stopServerMsg0 = new StopServerMsg();
      // Undeclared exception!
      try {
        stopServerMsg0.execute((BomberServer) null, (ClientInfo) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }
}
