/*
 * This file was automatically generated by EvoSuite
 */

package br.com.jnfe.base;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import br.com.jnfe.base.ModeloNFe;

public class ModeloNFeEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 br.com.jnfe.base.ModeloNFe.toString()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ModeloNFe modeloNFe0 = ModeloNFe._01;
      String string0 = modeloNFe0.toString();
      assertEquals("01", string0);
      assertNotNull(string0);
  }
}
