/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core.mock;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.DeployResultStatus;
import com.sap.netweaver.porta.core.mock.DeployResultMock;

public class DeployResultMockEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.core.mock.DeployResultMock.getStatus()Lcom/sap/netweaver/porta/core/DeployResultStatus;: root-Branch
   * 2 com.sap.netweaver.porta.core.mock.DeployResultMock.<init>(Lcom/sap/netweaver/porta/core/DeployResultStatus;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DeployResultStatus deployResultStatus0 = DeployResultStatus.ERROR;
      DeployResultMock deployResultMock0 = new DeployResultMock(deployResultStatus0, ",Ir| 1'y%&>GgCTF");
      DeployResultStatus deployResultStatus1 = deployResultMock0.getStatus();
      assertSame(deployResultStatus0, deployResultStatus1);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.core.mock.DeployResultMock.getStatusDetails()Ljava/lang/String;: root-Branch
   * 2 com.sap.netweaver.porta.core.mock.DeployResultMock.<init>(Lcom/sap/netweaver/porta/core/DeployResultStatus;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DeployResultStatus deployResultStatus0 = DeployResultStatus.ERROR;
      DeployResultMock deployResultMock0 = new DeployResultMock(deployResultStatus0, ",Ir| 1'y%&>GgCTF");
      String string0 = deployResultMock0.getStatusDetails();
      assertEquals(",Ir| 1'y%&>GgCTF", string0);
  }
}
