/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.xmlutil;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.EmptyStackException;
import nu.staldal.xmlutil.ContentHandlerFixer;
import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.Locator;
import org.xml.sax.SAXException;
import org.xml.sax.ext.Attributes2Impl;
import org.xml.sax.helpers.AttributesImpl;
import org.xml.sax.helpers.DefaultHandler;
import org.xml.sax.helpers.LocatorImpl;
import org.xml.sax.helpers.XMLFilterImpl;
import org.xml.sax.helpers.XMLReaderAdapter;

public class ContentHandlerFixerEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endPrefixMapping(Ljava/lang/String;)V: root-Branch
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;ZZ)V: root-Branch
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;Z)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.endPrefixMapping("");
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startDocument()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.startDocument();
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.skippedEntity(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.skippedEntity("");
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.characters([CII)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      char[] charArray0 = new char[2];
      contentHandlerFixer0.characters(charArray0, (-1214), 1424);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endDocument()V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.endDocument();
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.ignorableWhitespace([CII)V: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      char[] charArray0 = new char[10];
      contentHandlerFixer0.ignorableWhitespace(charArray0, (int) 'Z', (int) '~');
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.processingInstruction(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.processingInstruction((String) null, (String) null);
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.setDocumentLocator(Lorg/xml/sax/Locator;)V: root-Branch
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLFilterImpl0);
      LocatorImpl locatorImpl0 = new LocatorImpl();
      contentHandlerFixer0.setDocumentLocator((Locator) locatorImpl0);
      assertNull(locatorImpl0.getPublicId());
  }

  //Test case number: 8
  /*
   * 8 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I18 Branch 2 IFNULL L150 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I32 Branch 4 IFEQ L154 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I312 Branch 22 IFNE L230 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I352 Branch 24 IFEQ L243 - false
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I4 Branch 1 IFNE L143 - false
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I149 Branch 13 IF_ICMPGE L185 - true
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I250 Branch 19 IFEQ L211 - false
   * 8 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I260 Branch 20 IFEQ L215 - true
   */
  @Test
  public void test8()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true, true);
      Attributes2Impl attributes2Impl0 = new Attributes2Impl();
      contentHandlerFixer0.startElement("", (String) null, (String) null, (Attributes) attributes2Impl0);
      assertEquals(0, attributes2Impl0.getLength());
  }

  //Test case number: 9
  /*
   * 19 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I67 Branch 8 IFNULL L164 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I71 Branch 9 IF_ICMPGE L164 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I87 Branch 10 IFNULL L172 - false
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I91 Branch 11 IFLE L172 - true
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.genPrefix()Ljava/lang/String;: root-Branch
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I4 Branch 1 IFNE L143 - true
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I18 Branch 2 IFNULL L150 - false
   * 8 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I21 Branch 3 IFLE L150 - true
   * 9 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I32 Branch 4 IFEQ L154 - true
   * 10 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I49 Branch 5 IFNONNULL L161 - false
   * 11 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I60 Branch 6 IFNULL L164 - false
   * 12 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I64 Branch 7 IF_ICMPGE L164 - false
   * 13 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I117 Branch 12 IFNE L181 - true
   * 14 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I250 Branch 19 IFEQ L211 - true
   * 15 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I312 Branch 22 IFNE L230 - false
   * 16 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I322 Branch 23 IFEQ L232 - true
   * 17 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I322 Branch 23 IFEQ L232 - false
   * 18 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I352 Branch 24 IFEQ L243 - true
   * 19 nu.staldal.xmlutil.ContentHandlerFixer.startPrefixMapping(Ljava/lang/String;Ljava/lang/String;)V: I4 Branch 39 IFNE L307 - false
   */
  @Test
  public void test9()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLFilterImpl0);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      contentHandlerFixer0.startPrefixMapping("", "W");
      contentHandlerFixer0.startElement("", "W", "", (Attributes) attributesImpl0);
      assertEquals(0, attributesImpl0.getLength());
  }

  //Test case number: 10
  /*
   * 6 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I91 Branch 11 IFLE L172 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I278 Branch 21 IFNE L219 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I87 Branch 10 IFNULL L172 - false
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I64 Branch 7 IF_ICMPGE L164 - true
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I117 Branch 12 IFNE L181 - false
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I260 Branch 20 IFEQ L215 - false
   */
  @Test
  public void test10()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      contentHandlerFixer0.startPrefixMapping("", "v<9joy)XrcivJ5u'");
      contentHandlerFixer0.startElement("v<9joy)XrcivJ5u'", (String) null, "", (Attributes) attributesImpl0);
      assertEquals(0, attributesImpl0.getLength());
  }

  //Test case number: 11
  /*
   * 10 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I162 Branch 15 IFNE L188 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I49 Branch 5 IFNONNULL L161 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I67 Branch 8 IFNULL L164 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I149 Branch 13 IF_ICMPGE L185 - false
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I159 Branch 14 IFNULL L188 - false
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I162 Branch 15 IFNE L188 - false
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I179 Branch 16 IFEQ L192 - false
   * 8 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I182 Branch 17 IFEQ L192 - true
   * 9 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I198 Branch 18 IFNONNULL L199 - false
   * 10 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I278 Branch 21 IFNE L219 - true
   */
  @Test
  public void test11()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      ContentHandlerFixer contentHandlerFixer1 = new ContentHandlerFixer((ContentHandler) contentHandlerFixer0);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      attributesImpl0.addAttribute("xmlns", "6", "", "xmlns", "xmlns");
      contentHandlerFixer1.startElement("", "", "", (Attributes) attributesImpl0);
      assertFalse(contentHandlerFixer0.equals(contentHandlerFixer1));
  }

  //Test case number: 12
  /*
   * 4 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I179 Branch 16 IFEQ L192 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I64 Branch 7 IF_ICMPGE L164 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I67 Branch 8 IFNULL L164 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I117 Branch 12 IFNE L181 - false
   */
  @Test
  public void test12()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLFilterImpl0);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      attributesImpl0.addAttribute("", "", "", "", "");
      Attributes2Impl attributes2Impl0 = new Attributes2Impl((Attributes) attributesImpl0);
      contentHandlerFixer0.startElement("", "", "", (Attributes) attributes2Impl0);
      assertEquals(1, attributes2Impl0.getLength());
  }

  //Test case number: 13
  /*
   * 6 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I3 Branch 25 IFNULL L254 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I17 Branch 27 IFEQ L258 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I34 Branch 28 IFNONNULL L265 - false
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I45 Branch 29 IFNULL L268 - false
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I49 Branch 30 IF_ICMPGE L268 - true
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I72 Branch 33 IFNULL L276 - true
   */
  @Test
  public void test13()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      // Undeclared exception!
      try {
        contentHandlerFixer0.endElement("v<9joy)XrcivJ5u'", (String) null, (String) null);
        fail("Expecting exception: Error");
      } catch(Error e) {
        /*
         * No prefix for v<9joy)XrcivJ5u'
         */
      }
  }

  //Test case number: 14
  /*
   * 6 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I3 Branch 25 IFNULL L254 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I6 Branch 26 IFLE L254 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I127 Branch 36 IFEQ L287 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I140 Branch 37 IFNE L289 - false
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I150 Branch 38 IFEQ L291 - true
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I150 Branch 38 IFEQ L291 - false
   */
  @Test
  public void test14()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      // Undeclared exception!
      try {
        contentHandlerFixer0.endElement("+1m}1?#'AN=9QV5t{t", "+1m}1?#'AN=9QV5t{t", "+1m}1?#'AN=9QV5t{t");
        fail("Expecting exception: EmptyStackException");
      } catch(EmptyStackException e) {
      }
  }

  //Test case number: 15
  /*
   * 4 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I6 Branch 26 IFLE L254 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I49 Branch 30 IF_ICMPGE L268 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I52 Branch 31 IFNULL L268 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I103 Branch 35 IFNE L284 - false
   */
  @Test
  public void test15()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLFilterImpl0);
      // Undeclared exception!
      try {
        contentHandlerFixer0.endElement("", "", "");
        fail("Expecting exception: EmptyStackException");
      } catch(EmptyStackException e) {
      }
  }

  //Test case number: 16
  /*
   * 3 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I17 Branch 27 IFEQ L258 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I127 Branch 36 IFEQ L287 - false
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I140 Branch 37 IFNE L289 - true
   */
  @Test
  public void test16()  throws Throwable  {
      XMLReaderAdapter xMLReaderAdapter0 = new XMLReaderAdapter();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLReaderAdapter0, true, true);
      // Undeclared exception!
      try {
        contentHandlerFixer0.endElement("", "", "");
        fail("Expecting exception: EmptyStackException");
      } catch(EmptyStackException e) {
      }
  }

  //Test case number: 17
  /*
   * 3 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I34 Branch 28 IFNONNULL L265 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I103 Branch 35 IFNE L284 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I87 Branch 10 IFNULL L172 - true
   */
  @Test
  public void test17()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      contentHandlerFixer0.startElement("v<9joy)XrcivJ5u'", (String) null, "", (Attributes) attributesImpl0);
      contentHandlerFixer0.endElement("v<9joy)XrcivJ5u'", (String) null, (String) null);
  }

  //Test case number: 18
  /*
   * 7 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I52 Branch 31 IFNULL L268 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I56 Branch 32 IF_ICMPGE L268 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I72 Branch 33 IFNULL L276 - false
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I76 Branch 34 IFLE L276 - true
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I3 Branch 25 IFNULL L254 - false
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I6 Branch 26 IFLE L254 - true
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I49 Branch 30 IF_ICMPGE L268 - false
   */
  @Test
  public void test18()  throws Throwable  {
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) xMLFilterImpl0);
      contentHandlerFixer0.startPrefixMapping("", "_OW");
      // Undeclared exception!
      try {
        contentHandlerFixer0.endElement("", "", "");
        fail("Expecting exception: Error");
      } catch(Error e) {
        /*
         * No prefix for 
         */
      }
  }

  //Test case number: 19
  /*
   * 12 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I76 Branch 34 IFLE L276 - false
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I3 Branch 25 IFNULL L254 - true
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I17 Branch 27 IFEQ L258 - true
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I34 Branch 28 IFNONNULL L265 - false
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I45 Branch 29 IFNULL L268 - false
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I49 Branch 30 IF_ICMPGE L268 - true
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I72 Branch 33 IFNULL L276 - false
   * 8 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I103 Branch 35 IFNE L284 - false
   * 9 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I127 Branch 36 IFEQ L287 - true
   * 10 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I140 Branch 37 IFNE L289 - false
   * 11 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I150 Branch 38 IFEQ L291 - true
   * 12 nu.staldal.xmlutil.ContentHandlerFixer.endElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I150 Branch 38 IFEQ L291 - false
   */
  @Test
  public void test19()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      contentHandlerFixer0.startPrefixMapping("", "v<9joy)XrcivJ5u'");
      contentHandlerFixer0.endElement("v<9joy)XrcivJ5u'", (String) null, (String) null);
  }

  //Test case number: 20
  /*
   * 34 covered goals:
   * 1 nu.staldal.xmlutil.ContentHandlerFixer.startPrefixMapping(Ljava/lang/String;Ljava/lang/String;)V: I4 Branch 39 IFNE L307 - true
   * 2 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;)V: root-Branch
   * 3 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;ZZ)V: root-Branch
   * 4 nu.staldal.xmlutil.ContentHandlerFixer.<init>(Lorg/xml/sax/ContentHandler;Z)V: root-Branch
   * 5 nu.staldal.xmlutil.ContentHandlerFixer.genPrefix()Ljava/lang/String;: root-Branch
   * 6 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I4 Branch 1 IFNE L143 - true
   * 7 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I4 Branch 1 IFNE L143 - false
   * 8 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I18 Branch 2 IFNULL L150 - false
   * 9 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I21 Branch 3 IFLE L150 - true
   * 10 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I21 Branch 3 IFLE L150 - false
   * 11 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I32 Branch 4 IFEQ L154 - true
   * 12 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I49 Branch 5 IFNONNULL L161 - false
   * 13 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I60 Branch 6 IFNULL L164 - false
   * 14 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I64 Branch 7 IF_ICMPGE L164 - true
   * 15 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I87 Branch 10 IFNULL L172 - true
   * 16 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I117 Branch 12 IFNE L181 - true
   * 17 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I149 Branch 13 IF_ICMPGE L185 - true
   * 18 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I149 Branch 13 IF_ICMPGE L185 - false
   * 19 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I159 Branch 14 IFNULL L188 - false
   * 20 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I162 Branch 15 IFNE L188 - true
   * 21 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I162 Branch 15 IFNE L188 - false
   * 22 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I179 Branch 16 IFEQ L192 - false
   * 23 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I182 Branch 17 IFEQ L192 - true
   * 24 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I198 Branch 18 IFNONNULL L199 - false
   * 25 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I250 Branch 19 IFEQ L211 - true
   * 26 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I250 Branch 19 IFEQ L211 - false
   * 27 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I260 Branch 20 IFEQ L215 - true
   * 28 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I260 Branch 20 IFEQ L215 - false
   * 29 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I278 Branch 21 IFNE L219 - true
   * 30 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I312 Branch 22 IFNE L230 - false
   * 31 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I322 Branch 23 IFEQ L232 - true
   * 32 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I322 Branch 23 IFEQ L232 - false
   * 33 nu.staldal.xmlutil.ContentHandlerFixer.startElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;)V: I352 Branch 24 IFEQ L243 - true
   * 34 nu.staldal.xmlutil.ContentHandlerFixer.startPrefixMapping(Ljava/lang/String;Ljava/lang/String;)V: I4 Branch 39 IFNE L307 - false
   */
  @Test
  public void test20()  throws Throwable  {
      DefaultHandler defaultHandler0 = new DefaultHandler();
      ContentHandlerFixer contentHandlerFixer0 = new ContentHandlerFixer((ContentHandler) defaultHandler0, true);
      ContentHandlerFixer contentHandlerFixer1 = new ContentHandlerFixer((ContentHandler) contentHandlerFixer0);
      AttributesImpl attributesImpl0 = new AttributesImpl();
      attributesImpl0.addAttribute("xmlns", "6", "", "xmlns", "xmlns");
      contentHandlerFixer1.startElement("v<9joy)XrcivJ5u'", (String) null, "", (Attributes) attributesImpl0);
      assertFalse(contentHandlerFixer0.equals(contentHandlerFixer1));
  }
}
