/*
 * This file was automatically generated by EvoSuite
 */

package oasis.names.tc.ciq.xsdschema.xal._2;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;
import oasis.names.tc.ciq.xsdschema.xal._2.AddressLine;
import oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea;
import oasis.names.tc.ciq.xsdschema.xal._2.Locality;
import oasis.names.tc.ciq.xsdschema.xal._2.PostOffice;
import oasis.names.tc.ciq.xsdschema.xal._2.PostalCode;

public class AdministrativeAreaEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setPostalCode(Loasis/names/tc/ciq/xsdschema/xal/_2/PostalCode;)V: root-Branch
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      PostalCode postalCode0 = new PostalCode();
      administrativeArea_SubAdministrativeArea0.setPostalCode(postalCode0);
      assertNull(administrativeArea_SubAdministrativeArea0.getIndicator());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setIndicator(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea_SubAdministrativeArea0.setIndicator("S<B,pV4a.j");
      assertEquals("S<B,pV4a.j", administrativeArea_SubAdministrativeArea0.getIndicator());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setLocality(Loasis/names/tc/ciq/xsdschema/xal/_2/Locality;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea_SubAdministrativeArea0.setLocality((Locality) null);
      assertNull(administrativeArea_SubAdministrativeArea0.getUsageType());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getOtherAttributes()Ljava/util/Map;: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      Map<QName, String> map0 = administrativeArea_SubAdministrativeArea0.getOtherAttributes();
      assertEquals(0, map0.size());
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getLocality()Loasis/names/tc/ciq/xsdschema/xal/_2/Locality;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      Locality locality0 = administrativeArea_SubAdministrativeArea0.getLocality();
      assertNull(locality0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getType()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      String string0 = administrativeArea_SubAdministrativeArea0.getType();
      assertNull(string0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getUsageType()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      String string0 = administrativeArea_SubAdministrativeArea0.getUsageType();
      assertNull(string0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setPostOffice(Loasis/names/tc/ciq/xsdschema/xal/_2/PostOffice;)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea_SubAdministrativeArea0.setPostOffice((PostOffice) null);
      assertNull(administrativeArea_SubAdministrativeArea0.getIndicator());
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getIndicator()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      String string0 = administrativeArea_SubAdministrativeArea0.getIndicator();
      assertNull(string0);
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getPostOffice()Loasis/names/tc/ciq/xsdschema/xal/_2/PostOffice;: root-Branch
   */
  @Test
  public void test9()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      PostOffice postOffice0 = administrativeArea_SubAdministrativeArea0.getPostOffice();
      assertNull(postOffice0);
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getPostalCode()Loasis/names/tc/ciq/xsdschema/xal/_2/PostalCode;: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      PostalCode postalCode0 = administrativeArea_SubAdministrativeArea0.getPostalCode();
      assertNull(postalCode0);
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setType(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test11()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea_SubAdministrativeArea0.setType((String) null);
      assertNull(administrativeArea_SubAdministrativeArea0.getType());
  }

  //Test case number: 12
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.setUsageType(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test12()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea_SubAdministrativeArea0.setUsageType((String) null);
      assertNull(administrativeArea_SubAdministrativeArea0.getType());
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getType()Ljava/lang/String;: root-Branch
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.<init>()V: root-Branch
   */
  @Test
  public void test13()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      String string0 = administrativeArea0.getType();
      assertNull(string0);
  }

  //Test case number: 14
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getIndicator()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test14()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      String string0 = administrativeArea0.getIndicator();
      assertNull(string0);
  }

  //Test case number: 15
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getPostOffice()Loasis/names/tc/ciq/xsdschema/xal/_2/PostOffice;: root-Branch
   */
  @Test
  public void test15()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      PostOffice postOffice0 = administrativeArea0.getPostOffice();
      assertNull(postOffice0);
  }

  //Test case number: 16
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setPostOffice(Loasis/names/tc/ciq/xsdschema/xal/_2/PostOffice;)V: root-Branch
   */
  @Test
  public void test16()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      administrativeArea0.setPostOffice((PostOffice) null);
      assertNull(administrativeArea0.getType());
  }

  //Test case number: 17
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setLocality(Loasis/names/tc/ciq/xsdschema/xal/_2/Locality;)V: root-Branch
   */
  @Test
  public void test17()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      administrativeArea0.setLocality((Locality) null);
      assertNull(administrativeArea0.getIndicator());
  }

  //Test case number: 18
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getSubAdministrativeArea()Loasis/names/tc/ciq/xsdschema/xal/_2/AdministrativeArea$SubAdministrativeArea;: root-Branch
   */
  @Test
  public void test18()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = administrativeArea0.getSubAdministrativeArea();
      assertNull(administrativeArea_SubAdministrativeArea0);
  }

  //Test case number: 19
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setType(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test19()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      administrativeArea0.setType("-");
      assertNull(administrativeArea0.getUsageType());
  }

  //Test case number: 20
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setIndicator(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test20()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      administrativeArea0.setIndicator((String) null);
      assertNull(administrativeArea0.getType());
  }

  //Test case number: 21
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setUsageType(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test21()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      administrativeArea0.setUsageType("S<B,pV4a.j");
      assertNull(administrativeArea0.getType());
  }

  //Test case number: 22
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getPostalCode()Loasis/names/tc/ciq/xsdschema/xal/_2/PostalCode;: root-Branch
   */
  @Test
  public void test22()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      PostalCode postalCode0 = administrativeArea0.getPostalCode();
      assertNull(postalCode0);
  }

  //Test case number: 23
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getOtherAttributes()Ljava/util/Map;: root-Branch
   */
  @Test
  public void test23()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      Map<QName, String> map0 = administrativeArea0.getOtherAttributes();
      assertEquals(true, map0.isEmpty());
  }

  //Test case number: 24
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setSubAdministrativeArea(Loasis/names/tc/ciq/xsdschema/xal/_2/AdministrativeArea$SubAdministrativeArea;)V: root-Branch
   */
  @Test
  public void test24()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      administrativeArea0.setSubAdministrativeArea(administrativeArea_SubAdministrativeArea0);
      assertNull(administrativeArea_SubAdministrativeArea0.getType());
  }

  //Test case number: 25
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.setPostalCode(Loasis/names/tc/ciq/xsdschema/xal/_2/PostalCode;)V: root-Branch
   */
  @Test
  public void test25()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      PostalCode postalCode0 = new PostalCode();
      administrativeArea0.setPostalCode(postalCode0);
      assertNull(administrativeArea0.getIndicator());
  }

  //Test case number: 26
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getUsageType()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test26()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      String string0 = administrativeArea0.getUsageType();
      assertNull(string0);
  }

  //Test case number: 27
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getLocality()Loasis/names/tc/ciq/xsdschema/xal/_2/Locality;: root-Branch
   */
  @Test
  public void test27()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      Locality locality0 = administrativeArea0.getLocality();
      assertNull(locality0);
  }

  //Test case number: 28
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.getType()Ljava/lang/String;: root-Branch
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.<init>()V: root-Branch
   */
  @Test
  public void test28()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      String string0 = administrativeArea_AdministrativeAreaName0.getType();
      assertNull(string0);
  }

  //Test case number: 29
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.setContent(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test29()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      administrativeArea_AdministrativeAreaName0.setContent("S<B,pV4a.j");
      assertNull(administrativeArea_AdministrativeAreaName0.getType());
  }

  //Test case number: 30
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.getContent()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test30()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      String string0 = administrativeArea_AdministrativeAreaName0.getContent();
      assertNull(string0);
  }

  //Test case number: 31
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.getOtherAttributes()Ljava/util/Map;: root-Branch
   */
  @Test
  public void test31()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      Map<QName, String> map0 = administrativeArea_AdministrativeAreaName0.getOtherAttributes();
      assertEquals(true, map0.isEmpty());
  }

  //Test case number: 32
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.setType(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test32()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      administrativeArea_AdministrativeAreaName0.setType("S<B,pV4a.j");
      assertNull(administrativeArea_AdministrativeAreaName0.getContent());
  }

  //Test case number: 33
  /*
   * 1 covered goal:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.setCode(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test33()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      administrativeArea_AdministrativeAreaName0.setCode("S<B,pV4a.j");
      assertEquals("S<B,pV4a.j", administrativeArea_AdministrativeAreaName0.getCode());
  }

  //Test case number: 34
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.getCode()Ljava/lang/String;: root-Branch
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$AdministrativeAreaName.<init>()V: root-Branch
   */
  @Test
  public void test34()  throws Throwable  {
      AdministrativeArea.AdministrativeAreaName administrativeArea_AdministrativeAreaName0 = new AdministrativeArea.AdministrativeAreaName();
      String string0 = administrativeArea_AdministrativeAreaName0.getCode();
      assertNull(string0);
  }

  //Test case number: 35
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAddressLine()Ljava/util/List;: I4 Branch 1 IFNONNULL L162 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAddressLine()Ljava/util/List;: I4 Branch 1 IFNONNULL L162 - false
   */
  @Test
  public void test35()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      List<AddressLine> list0 = administrativeArea0.getAddressLine();
      List<AddressLine> list1 = administrativeArea0.getAddressLine();
      assertNotNull(list1);
      assertSame(list1, list0);
  }

  //Test case number: 36
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAdministrativeAreaName()Ljava/util/List;: I4 Branch 2 IFNONNULL L191 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAdministrativeAreaName()Ljava/util/List;: I4 Branch 2 IFNONNULL L191 - false
   */
  @Test
  public void test36()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      List<AdministrativeArea.AdministrativeAreaName> list0 = administrativeArea0.getAdministrativeAreaName();
      List<AdministrativeArea.AdministrativeAreaName> list1 = administrativeArea0.getAdministrativeAreaName();
      assertSame(list1, list0);
      assertNotNull(list1);
  }

  //Test case number: 37
  /*
   * 3 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAny()Ljava/util/List;: I4 Branch 3 IFNONNULL L316 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.getAny()Ljava/util/List;: I4 Branch 3 IFNONNULL L316 - false
   * 3 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea.<init>()V: root-Branch
   */
  @Test
  public void test37()  throws Throwable  {
      AdministrativeArea administrativeArea0 = new AdministrativeArea();
      List<Object> list0 = administrativeArea0.getAny();
      List<Object> list1 = administrativeArea0.getAny();
      assertSame(list1, list0);
      assertNotNull(list1);
  }

  //Test case number: 38
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getAddressLine()Ljava/util/List;: I4 Branch 4 IFNONNULL L640 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getAddressLine()Ljava/util/List;: I4 Branch 4 IFNONNULL L640 - false
   */
  @Test
  public void test38()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      List<AddressLine> list0 = administrativeArea_SubAdministrativeArea0.getAddressLine();
      List<AddressLine> list1 = administrativeArea_SubAdministrativeArea0.getAddressLine();
      assertSame(list1, list0);
      assertNotNull(list1);
  }

  //Test case number: 39
  /*
   * 2 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getSubAdministrativeAreaName()Ljava/util/List;: I4 Branch 5 IFNONNULL L669 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getSubAdministrativeAreaName()Ljava/util/List;: I4 Branch 5 IFNONNULL L669 - false
   */
  @Test
  public void test39()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      List<AdministrativeArea.SubAdministrativeArea.SubAdministrativeAreaName> list0 = administrativeArea_SubAdministrativeArea0.getSubAdministrativeAreaName();
      List<AdministrativeArea.SubAdministrativeArea.SubAdministrativeAreaName> list1 = administrativeArea_SubAdministrativeArea0.getSubAdministrativeAreaName();
      assertNotNull(list1);
      assertSame(list1, list0);
  }

  //Test case number: 40
  /*
   * 3 covered goals:
   * 1 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getAny()Ljava/util/List;: I4 Branch 6 IFNONNULL L770 - true
   * 2 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.getAny()Ljava/util/List;: I4 Branch 6 IFNONNULL L770 - false
   * 3 oasis.names.tc.ciq.xsdschema.xal._2.AdministrativeArea$SubAdministrativeArea.<init>()V: root-Branch
   */
  @Test
  public void test40()  throws Throwable  {
      AdministrativeArea.SubAdministrativeArea administrativeArea_SubAdministrativeArea0 = new AdministrativeArea.SubAdministrativeArea();
      List<Object> list0 = administrativeArea_SubAdministrativeArea0.getAny();
      List<Object> list1 = administrativeArea_SubAdministrativeArea0.getAny();
      assertNotNull(list1);
      assertSame(list1, list0);
  }
}
