/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.core;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.core.CoreException;
import com.sap.netweaver.porta.core.ServerFactory;
import java.util.Properties;

public class ServerFactoryEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.core.ServerFactory.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ServerFactory serverFactory0 = new ServerFactory();
      assertNotNull(serverFactory0);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 com.sap.netweaver.porta.core.ServerFactory.createServer(Ljava/util/Properties;)Lcom/sap/netweaver/porta/core/Server;: I3 Branch 1 IFNONNULL L131 - true
   * 2 com.sap.netweaver.porta.core.ServerFactory.createServer(Ljava/util/Properties;)Lcom/sap/netweaver/porta/core/Server;: I20 Branch 2 IFNONNULL L136 - false
   */
  @Test
  public void test1()  throws Throwable  {
      Properties properties0 = new Properties();
      // Undeclared exception!
      try {
        ServerFactory.createServer(properties0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * server.type property missing
         */
      }
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.core.ServerFactory.createServer(Ljava/util/Properties;)Lcom/sap/netweaver/porta/core/Server;: I3 Branch 1 IFNONNULL L131 - false
   */
  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        ServerFactory.createServer((Properties) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
        /*
         * properties cannot be null
         */
      }
  }
}
