/*
 * This file was automatically generated by EvoSuite
 */

package client.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import client.gui.GlobalHighscoreLobby;
import db.DBGameUser;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.util.ArrayList;

@RunWith(EvoSuiteRunner.class)
public class GlobalHighscoreLobbyEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 client.gui.GlobalHighscoreLobby.updateHighscore()V: root-Branch
   * 2 client.gui.GlobalHighscoreLobby.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      globalHighscoreLobby0.updateHighscore();
      assertEquals(0.5F, globalHighscoreLobby0.getAlignmentY(), 0.01F);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 client.gui.GlobalHighscoreLobby.mouseExited(Ljava/awt/event/MouseEvent;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      MouseEvent mouseEvent0 = new MouseEvent((Component) globalHighscoreLobby0, 382, (long) 382, (-1021), (-1918), (-1881), (-768), false);
      globalHighscoreLobby0.mouseExited(mouseEvent0);
      assertEquals(false, globalHighscoreLobby0.isMinimumSizeSet());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 client.gui.GlobalHighscoreLobby.mouseReleased(Ljava/awt/event/MouseEvent;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) globalHighscoreLobby0, 480, (long) 480, 0, (-1750), 480, (-1750), true, 0, 0, 1813);
      globalHighscoreLobby0.mouseReleased((MouseEvent) mouseWheelEvent0);
      assertEquals(false, mouseWheelEvent0.isShiftDown());
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 client.gui.GlobalHighscoreLobby.fillScore(Ljava/util/ArrayList;)V: I15 Branch 1 IF_ICMPGE L118 - true
   * 2 client.gui.GlobalHighscoreLobby.<init>()V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      ArrayList<DBGameUser> arrayList0 = new ArrayList<DBGameUser>();
      globalHighscoreLobby0.fillScore(arrayList0);
      assertEquals(true, globalHighscoreLobby0.isEnabled());
  }
}
