/*
 * This file was automatically generated by EvoSuite
 */

package com.allenstudio.ir.ui.calendar;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.allenstudio.ir.ui.calendar.MonthlyCalendar;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.util.GregorianCalendar;
import javax.swing.JComponent;
import javax.swing.JRadioButton;
import javax.swing.JToolTip;

public class MonthlyCalendarEvoSuiteTest {


  //Test case number: 0
  /*
   * 12 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.getHighlightBackground()Ljava/awt/Color;: root-Branch
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.<init>()V: root-Branch
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I3 Branch 1 IFEQ L176 - false
   * 4 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I6 Branch 2 IFNE L176 - false
   * 5 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I19 Branch 12 IF_ICMPNE L246 - true
   * 6 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I65 Branch 14 IFEQ L256 - false
   * 7 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I88 Branch 15 IF_ICMPGE L261 - true
   * 8 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I88 Branch 15 IF_ICMPGE L261 - false
   * 9 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I107 Branch 16 IF_ICMPGE L264 - true
   * 10 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I107 Branch 16 IF_ICMPGE L264 - false
   * 11 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I132 Branch 17 IF_ICMPGE L267 - true
   * 12 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I132 Branch 17 IF_ICMPGE L267 - false
   */
  @Test
  public void test0()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      Color color0 = monthlyCalendar0.getHighlightBackground();
      assertEquals("com.allenstudio.ir.ui.calendar.MonthlyCalendar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=189,height=140]]", monthlyCalendar0.toString());
      assertNotNull(color0);
      assertEquals(0, color0.getRed());
      assertEquals(2015, monthlyCalendar0.getYear());
      assertEquals(true, monthlyCalendar0.getMouseListeningEnabled());
      assertEquals(6, monthlyCalendar0.getMonth());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.getHeaderComponent()Ljavax/swing/JComponent;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      monthlyCalendar0.getHeaderComponent();
      assertEquals(2015, monthlyCalendar0.getYear());
      assertEquals(6, monthlyCalendar0.getMonth());
      assertEquals(true, monthlyCalendar0.getMouseListeningEnabled());
      assertEquals("com.allenstudio.ir.ui.calendar.MonthlyCalendar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=189,height=140]]", monthlyCalendar0.toString());
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I3 Branch 1 IFEQ L176 - true
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I21 Branch 3 IFNE L179 - false
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I24 Branch 4 IFEQ L179 - false
   */
  @Test
  public void test2()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      monthlyCalendar0.setMouseListeningEnabled(false);
      assertEquals(2015, monthlyCalendar0.getYear());
      assertEquals("com.allenstudio.ir.ui.calendar.MonthlyCalendar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=189,height=140]]", monthlyCalendar0.toString());
      assertEquals(6, monthlyCalendar0.getMonth());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYear(I)V: I4 Branch 5 IF_ICMPGE L201 - false
   */
  @Test
  public void test3()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      // Undeclared exception!
      try {
        monthlyCalendar0.setYear((-1930));
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Year must be later than 1970!
         */
      }
  }

  //Test case number: 4
  /*
   * 7 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMonth(I)V: I4 Branch 7 IF_ICMPLT L216 - false
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMonth(I)V: I7 Branch 8 IF_ICMPLE L216 - true
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMonth(I)V: I20 Branch 9 IF_ICMPEQ L218 - false
   * 4 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(II)V: I5 Branch 10 IF_ICMPNE L232 - false
   * 5 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(II)V: I9 Branch 11 IF_ICMPNE L232 - true
   * 6 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I19 Branch 12 IF_ICMPNE L246 - false
   * 7 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I23 Branch 13 IF_ICMPNE L246 - true
   */
  @Test
  public void test4()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      monthlyCalendar0.setMonth(10);
      assertEquals(10, monthlyCalendar0.getMonth());
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.resize()V: I8 Branch 19 IFNULL L400 - true
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.resize()V: I63 Branch 20 IFNONNULL L409 - true
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setHeaderComponent(Ljavax/swing/JComponent;)V: I12 Branch 21 IFNULL L439 - false
   */
  @Test
  public void test5()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      JRadioButton jRadioButton0 = new JRadioButton();
      JToolTip jToolTip0 = jRadioButton0.createToolTip();
      monthlyCalendar0.setHeaderComponent((JComponent) jToolTip0);
      assertEquals(1, monthlyCalendar0.getComponentCount());
      assertEquals(6, monthlyCalendar0.getMonth());
  }

  //Test case number: 6
  /*
   * 4 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.paintComponent(Ljava/awt/Graphics;)V: I9 Branch 22 IFNONNULL L468 - false
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.paintComponent(Ljava/awt/Graphics;)V: I17 Branch 23 IF_ICMPGE L469 - false
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.paintComponent(Ljava/awt/Graphics;)V: I22 Branch 24 IFEQ L471 - false
   * 4 com.allenstudio.ir.ui.calendar.MonthlyCalendar.paintSymbol(Ljava/awt/Graphics;Ljava/awt/Font;Ljava/awt/Color;Ljava/awt/Color;Ljava/lang/String;IIII)V: I3 Branch 40 IFNONNULL L526 - true
   */
  @Test
  public void test6()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      // Undeclared exception!
      try {
        monthlyCalendar0.paintComponent((Graphics) null);
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
      }
  }

  //Test case number: 7
  /*
   * 3 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.getSelectedDate()Ljava/util/Calendar;: I34 Branch 41 IF_ICMPLE L561 - false
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.getDayOfMonth(II)I: I58 Branch 57 IFNE L704 - true
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.getDayOfMonth(II)I: I67 Branch 59 IFNE L704 - true
   */
  @Test
  public void test7()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      GregorianCalendar gregorianCalendar0 = (GregorianCalendar)monthlyCalendar0.getSelectedDate();
      assertEquals(30, monthlyCalendar0.getSelectedDay());
      assertEquals(1435718385661L, gregorianCalendar0.getTimeInMillis());
  }

  //Test case number: 8
  /*
   * 16 covered goals:
   * 1 com.allenstudio.ir.ui.calendar.MonthlyCalendar.mouseMoved(Ljava/awt/event/MouseEvent;)V: I5 Branch 49 IF_ACMPEQ L652 - true
   * 2 com.allenstudio.ir.ui.calendar.MonthlyCalendar.mousePositionChanged(Ljava/awt/event/MouseEvent;)V: I36 Branch 51 IFLT L678 - false
   * 3 com.allenstudio.ir.ui.calendar.MonthlyCalendar.mousePositionChanged(Ljava/awt/event/MouseEvent;)V: I39 Branch 52 IF_ICMPGE L678 - false
   * 4 com.allenstudio.ir.ui.calendar.MonthlyCalendar.mousePositionChanged(Ljava/awt/event/MouseEvent;)V: I41 Branch 53 IFLT L678 - true
   * 5 com.allenstudio.ir.ui.calendar.MonthlyCalendar.mousePositionChanged(Ljava/awt/event/MouseEvent;)V: I50 Branch 55 IF_ICMPEQ L679 - true
   * 6 com.allenstudio.ir.ui.calendar.MonthlyCalendar.<init>()V: root-Branch
   * 7 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I19 Branch 12 IF_ICMPNE L246 - true
   * 8 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I65 Branch 14 IFEQ L256 - false
   * 9 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I88 Branch 15 IF_ICMPGE L261 - true
   * 10 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I88 Branch 15 IF_ICMPGE L261 - false
   * 11 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I107 Branch 16 IF_ICMPGE L264 - true
   * 12 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I107 Branch 16 IF_ICMPGE L264 - false
   * 13 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I132 Branch 17 IF_ICMPGE L267 - true
   * 14 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setYearMonth(Ljava/util/Calendar;)V: I132 Branch 17 IF_ICMPGE L267 - false
   * 15 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I3 Branch 1 IFEQ L176 - false
   * 16 com.allenstudio.ir.ui.calendar.MonthlyCalendar.setMouseListeningEnabled(Z)V: I6 Branch 2 IFNE L176 - false
   */
  @Test
  public void test8()  throws Throwable  {
      MonthlyCalendar monthlyCalendar0 = new MonthlyCalendar();
      assertNotNull(monthlyCalendar0);
      
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) monthlyCalendar0, 122, (long) 122, (-1518), 122, (-1518), 0, 9, 1051, true, 1081, 9, (-46));
      monthlyCalendar0.mouseMoved((MouseEvent) mouseWheelEvent0);
      assertEquals(6, monthlyCalendar0.getMonth());
      assertEquals(2015, monthlyCalendar0.getYear());
      assertEquals("java.awt.event.MouseWheelEvent[unknown type,(122,-1518),absolute(0,9),button=0,modifiers=Ctrl+Button1+Button2+Button3,extModifiers=Alt+Alt Graph+Button2+Button3+Button4+Button5+Button6+Button7+Button8+Button9+Button10+Button11+Button12+Button13+Button14+Button15+Button16+Button17+Button18+Button19+Button20,clickCount=1051,scrollType=unknown scroll type,scrollAmount=9,wheelRotation=-46,preciseWheelRotation=-46.0] on com.allenstudio.ir.ui.calendar.MonthlyCalendar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=189,height=140]]", mouseWheelEvent0.toString());
      assertEquals(true, monthlyCalendar0.getWeekStartOnSunday());
      assertEquals("com.allenstudio.ir.ui.calendar.MonthlyCalendar[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=189,height=140]]", monthlyCalendar0.toString());
  }
}
