/*
 * This file was automatically generated by EvoSuite
 */

package common;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import common.PowerUp;
import common.Tile;
import java.awt.Point;

@RunWith(EvoSuiteRunner.class)
public class GameObjectEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 common.GameObject.setActive()V: root-Branch
   * 2 common.GameObject.setInvisible()V: root-Branch
   * 3 common.GameObject.<init>(Ljava/awt/Point;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      PowerUp powerUp0 = new PowerUp((Point) null);
      assertEquals(true, powerUp0.isActive());
      assertEquals(false, powerUp0.isVisible());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 common.GameObject.getId()I: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Tile tile0 = new Tile((Point) null);
      int int0 = tile0.getId();
      assertEquals(true, tile0.isActive());
      assertEquals(0, int0);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 common.GameObject.getPosition()Ljava/awt/Point;: root-Branch
   * 2 common.GameObject.<init>(Ljava/awt/Point;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      Tile tile0 = new Tile((Point) null);
      tile0.getPosition();
      assertEquals(true, tile0.isActive());
  }
}
