/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.config;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.Map;
import org.jsecurity.config.ConfigurationException;
import org.jsecurity.config.ReflectionBuilder;
import org.jsecurity.config.UnresolveableReferenceException;
import org.jsecurity.util.Nameable;

public class ReflectionBuilderEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.getObjects()Ljava/util/Map;: root-Branch
   * 2 org.jsecurity.config.ReflectionBuilder.setObjects(Ljava/util/Map;)V: root-Branch
   * 3 org.jsecurity.config.ReflectionBuilder.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      Map<Object, Object> map0 = reflectionBuilder0.getObjects();
      assertEquals(true, map0.isEmpty());
  }

  //Test case number: 1
  /*
   * 8 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.getId(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * 2 org.jsecurity.config.ReflectionBuilder.isReference(Ljava/lang/String;)Z: I3 Branch 16 IFNULL L179 - false
   * 3 org.jsecurity.config.ReflectionBuilder.isReference(Ljava/lang/String;)Z: I8 Branch 17 IFLE L179 - false
   * 4 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I4 Branch 18 IFNULL L187 - false
   * 5 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I8 Branch 19 IFGT L187 - true
   * 6 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I21 Branch 20 IFNONNULL L188 - false
   * 7 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 23 IFEQ L208 - false
   * 8 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V: I16 Branch 24 IFEQ L210 - true
   */
  @Test
  public void test1()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      // Undeclared exception!
      try {
        reflectionBuilder0.applyProperty((Object) "$ce$:d(kzv]=$ce$:d(kzv]", "$ce$:d(kzv]=$ce$:d(kzv]", "$ce$:d(kzv]=$ce$:d(kzv]");
        fail("Expecting exception: UnresolveableReferenceException");
      } catch(UnresolveableReferenceException e) {
        /*
         * The object with id [ce$:d(kzv]=$ce$:d(kzv]] has not yet been defined and therefore cannot be referenced.  Please ensure objects are defined in the order in which they should be created and made avaialable for future reference.
         */
      }
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I3 Branch 1 IFNULL L73 - true
   */
  @Test
  public void test2()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      Map<Object, Object> map0 = reflectionBuilder0.buildObjects((Map<String, String>) null);
      assertEquals(0, map0.size());
  }

  //Test case number: 3
  /*
   * 3 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.applyGlobalProperty(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)V: I9 Branch 12 IFEQ L145 - true
   * 2 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I6 Branch 2 IFGT L73 - true
   * 3 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I3 Branch 1 IFNULL L73 - false
   */
  @Test
  public void test3()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Map<Object, Object> map0 = reflectionBuilder0.buildObjects((Map<String, String>) hashMap0);
      reflectionBuilder0.applyGlobalProperty((Map) map0, "$ce$:d(kzv]", "$ce$:d(kzv]");
      assertEquals(0, map0.size());
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I6 Branch 2 IFGT L73 - false
   * 2 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I28 Branch 3 IFEQ L79 - true
   * 3 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I28 Branch 3 IFEQ L79 - false
   * 4 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I40 Branch 4 IFLT L80 - true
   * 5 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I78 Branch 6 IFEQ L88 - false
   * 6 org.jsecurity.config.ReflectionBuilder.createNewInstance(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)V: I9 Branch 8 IFNULL L104 - true
   */
  @Test
  public void test4()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      hashMap0.put("$[CUSTOM LOG FACTORY] was loaded by the boot classloader", "$[CUSTOM LOG FACTORY] was loaded by the boot classloader");
      // Undeclared exception!
      try {
        reflectionBuilder0.buildObjects((Map<String, String>) hashMap0);
        fail("Expecting exception: ConfigurationException");
      } catch(ConfigurationException e) {
        /*
         * Unable to instantiate class [$[CUSTOM LOG FACTORY] was loaded by the boot classloader] for object named '$[CUSTOM LOG FACTORY] was loaded by the boot classloader'.  Please ensure you've specified the fully qualified class name correctly.
         */
      }
  }

  //Test case number: 5
  /*
   * 8 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I40 Branch 4 IFLT L80 - false
   * 2 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I46 Branch 5 IFLE L80 - true
   * 3 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I78 Branch 6 IFEQ L88 - true
   * 4 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I107 Branch 7 IFEQ L93 - false
   * 5 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V: I9 Branch 10 IFLT L127 - false
   * 6 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V: I32 Branch 11 IFLE L131 - true
   * 7 org.jsecurity.config.ReflectionBuilder.applySingleProperty(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I11 Branch 14 IFLE L162 - true
   * 8 org.jsecurity.config.ReflectionBuilder.applySingleProperty(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I22 Branch 15 IFNONNULL L166 - false
   */
  @Test
  public void test5()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      hashMap0.put("V.C)*)ptX$m", "V.C)*)ptX$m");
      // Undeclared exception!
      try {
        reflectionBuilder0.buildObjects((Map<String, String>) hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Configuration error.  Specified object [V] with property [C)*)ptX$m] without first defining that object's class.  Please first specify the class property first, e.g. myObject.class = fully_qualified_class_name and then define additional properties.
         */
      }
  }

  //Test case number: 6
  /*
   * 7 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.createNewInstance(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)V: I9 Branch 8 IFNULL L104 - false
   * 2 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I3 Branch 1 IFNULL L73 - false
   * 3 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I6 Branch 2 IFGT L73 - false
   * 4 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I28 Branch 3 IFEQ L79 - true
   * 5 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I28 Branch 3 IFEQ L79 - false
   * 6 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I40 Branch 4 IFLT L80 - true
   * 7 org.jsecurity.config.ReflectionBuilder.buildObjects(Ljava/util/Map;)Ljava/util/Map;: I78 Branch 6 IFEQ L88 - false
   */
  @Test
  public void test6()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      reflectionBuilder0.setObjects((Map) hashMap0);
      hashMap0.put("$[CSTOM LOG FACTORY] was loaded by the boot classloader", "$[CSTOM LOG FACTORY] was loaded by the boot classloader");
      // Undeclared exception!
      try {
        reflectionBuilder0.buildObjects((Map<String, String>) hashMap0);
        fail("Expecting exception: ConfigurationException");
      } catch(ConfigurationException e) {
        /*
         * Unable to instantiate class [$[CSTOM LOG FACTORY] was loaded by the boot classloader] for object named '$[CSTOM LOG FACTORY] was loaded by the boot classloader'.  Please ensure you've specified the fully qualified class name correctly.
         */
      }
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;)V: I9 Branch 10 IFLT L127 - true
   */
  @Test
  public void test7()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<Nameable, String> hashMap0 = new HashMap<Nameable, String>();
      // Undeclared exception!
      try {
        reflectionBuilder0.applyProperty("TgZ\" ", "TgZ\" ", (Map) hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * All property keys must contain a '.' character. (e.g. myBean.property = value)  These should already be separated out by buildObjects().
         */
      }
  }

  //Test case number: 8
  /*
   * 9 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.applySingleProperty(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I22 Branch 15 IFNONNULL L166 - true
   * 2 org.jsecurity.config.ReflectionBuilder.isReference(Ljava/lang/String;)Z: I8 Branch 17 IFLE L179 - true
   * 3 org.jsecurity.config.ReflectionBuilder.unescapeIfNecessary(Ljava/lang/String;)Ljava/lang/String;: I3 Branch 21 IFNULL L198 - false
   * 4 org.jsecurity.config.ReflectionBuilder.unescapeIfNecessary(Ljava/lang/String;)Ljava/lang/String;: I8 Branch 22 IFLE L198 - true
   * 5 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V: I5 Branch 23 IFEQ L208 - true
   * 6 org.jsecurity.config.ReflectionBuilder.applyProperty(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)V: I56 Branch 25 IFEQ L220 - true
   * 7 org.jsecurity.config.ReflectionBuilder.isReference(Ljava/lang/String;)Z: I3 Branch 16 IFNULL L179 - false
   * 8 org.jsecurity.config.ReflectionBuilder.applySingleProperty(Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V: I11 Branch 14 IFLE L162 - true
   * 9 org.jsecurity.config.ReflectionBuilder.<init>(Ljava/util/Map;)V: root-Branch
   */
  @Test
  public void test8()  throws Throwable  {
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder((Map) hashMap0);
      hashMap0.put("$[CUSTOM LOG FACTORY] LogFactory class cannot be loaded by classloader which loaded the custom LogFactory implementation. Is the custom factory in the right classloader?", "$[CUSTOM LOG FACTORY] LogFactory class cannot be loaded by classloader which loaded the custom LogFactory implementation. Is the custom factory in the right classloader?");
      // Undeclared exception!
      try {
        reflectionBuilder0.applySingleProperty((Map) hashMap0, "$[CUSTOM LOG FACTORY] LogFactory class cannot be loaded by classloader which loaded the custom LogFactory implementation. Is the custom factory in the right classloader?", "hSC55Z3Z]E", "hSC55Z3Z]E");
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * org/apache/commons/beanutils/BeanUtils
         */
      }
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.jsecurity.config.ReflectionBuilder.isReference(Ljava/lang/String;)Z: I3 Branch 16 IFNULL L179 - true
   */
  @Test
  public void test9()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      boolean boolean0 = reflectionBuilder0.isReference((String) null);
      assertEquals(false, boolean0);
  }

  //Test case number: 10
  /*
   * 3 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I4 Branch 18 IFNULL L187 - true
   * 2 org.jsecurity.config.ReflectionBuilder.<init>(Ljava/util/Map;)V: root-Branch
   * 3 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I21 Branch 20 IFNONNULL L188 - false
   */
  @Test
  public void test10()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder((Map) null);
      // Undeclared exception!
      try {
        reflectionBuilder0.getReferencedObject("!)bp$ RLtJr>Q");
        fail("Expecting exception: UnresolveableReferenceException");
      } catch(UnresolveableReferenceException e) {
        /*
         * The object with id [!)bp$ RLtJr>Q] has not yet been defined and therefore cannot be referenced.  Please ensure objects are defined in the order in which they should be created and made avaialable for future reference.
         */
      }
  }

  //Test case number: 11
  /*
   * 3 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I8 Branch 19 IFGT L187 - false
   * 2 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I21 Branch 20 IFNONNULL L188 - true
   * 3 org.jsecurity.config.ReflectionBuilder.getReferencedObject(Ljava/lang/String;)Ljava/lang/Object;: I4 Branch 18 IFNULL L187 - false
   */
  @Test
  public void test11()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      reflectionBuilder0.setObjects((Map) hashMap0);
      hashMap0.put("", "");
      String string0 = (String)reflectionBuilder0.getReferencedObject("");
      assertEquals("", string0);
  }

  //Test case number: 12
  /*
   * 3 covered goals:
   * 1 org.jsecurity.config.ReflectionBuilder.unescapeIfNecessary(Ljava/lang/String;)Ljava/lang/String;: I3 Branch 21 IFNULL L198 - true
   * 2 org.jsecurity.config.ReflectionBuilder.setObjects(Ljava/util/Map;)V: root-Branch
   * 3 org.jsecurity.config.ReflectionBuilder.<init>()V: root-Branch
   */
  @Test
  public void test12()  throws Throwable  {
      ReflectionBuilder reflectionBuilder0 = new ReflectionBuilder();
      String string0 = reflectionBuilder0.unescapeIfNecessary((String) null);
      assertNull(string0);
  }
}
