/*
 * This file was automatically generated by EvoSuite
 */

package client.gui;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import client.gui.GlobalHighscoreLobby;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;

@RunWith(EvoSuiteRunner.class)
public class GlobalHighscoreLobbyEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 client.gui.GlobalHighscoreLobby.updateHighscore()V: root-Branch
   * 2 client.gui.GlobalHighscoreLobby.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      globalHighscoreLobby0.updateHighscore();
      assertEquals(true, globalHighscoreLobby0.isEnabled());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 client.gui.GlobalHighscoreLobby.mouseClicked(Ljava/awt/event/MouseEvent;)V: I7 Branch 13 IFEQ L185 - true
   */
  @Test
  public void test1()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent((Component) globalHighscoreLobby0, (-1290), (long) (-1290), (-1290), (-536), (-1290), 1465, true, 0, 0, 410);
      globalHighscoreLobby0.mouseClicked((MouseEvent) mouseWheelEvent0);
      assertEquals(true, globalHighscoreLobby0.isFocusTraversable());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 client.gui.GlobalHighscoreLobby.actionPerformed(Ljava/awt/event/ActionEvent;)V: I7 Branch 14 IFEQ L214 - true
   * 2 client.gui.GlobalHighscoreLobby.<init>()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      GlobalHighscoreLobby globalHighscoreLobby0 = new GlobalHighscoreLobby();
      ActionEvent actionEvent0 = new ActionEvent((Object) "SwingDisplayedMnemonicIndexKey", (-1079), "Ni", (-2013L), (-1079));
      globalHighscoreLobby0.actionPerformed(actionEvent0);
      assertEquals(true, globalHighscoreLobby0.isFocusable());
  }
}
