/*
 * This file was automatically generated by EvoSuite
 */

package nu.staldal.xtree;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import nu.staldal.xtree.ProcessingInstruction;
import org.xml.sax.ContentHandler;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.XMLFilterImpl;

public class ProcessingInstructionEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 nu.staldal.xtree.ProcessingInstruction.toSAX(Lorg/xml/sax/ContentHandler;)V: root-Branch
   * 2 nu.staldal.xtree.ProcessingInstruction.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      ProcessingInstruction processingInstruction0 = new ProcessingInstruction("@$kh%/0puJ*v8##", "@$kh%/0puJ*v8##");
      XMLFilterImpl xMLFilterImpl0 = new XMLFilterImpl();
      processingInstruction0.toSAX((ContentHandler) xMLFilterImpl0);
      assertEquals("@$kh%/0puJ*v8##", processingInstruction0.getValue());
      assertEquals("@$kh%/0puJ*v8##", processingInstruction0.getTarget());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 nu.staldal.xtree.ProcessingInstruction.getTarget()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      ProcessingInstruction processingInstruction0 = new ProcessingInstruction("@$kh%/0puJ*v8##", "@$kh%/0puJ*v8##");
      String string0 = processingInstruction0.getTarget();
      assertNotNull(string0);
      assertEquals("@$kh%/0puJ*v8##", string0);
      assertEquals("@$kh%/0puJ*v8##", processingInstruction0.getValue());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 nu.staldal.xtree.ProcessingInstruction.getValue()Ljava/lang/String;: root-Branch
   * 2 nu.staldal.xtree.ProcessingInstruction.<init>(Ljava/lang/String;Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      ProcessingInstruction processingInstruction0 = new ProcessingInstruction("@$kh%/0puJ*v8##", "@$kh%/0puJ*v8##");
      String string0 = processingInstruction0.getValue();
      assertEquals("@$kh%/0puJ*v8##", string0);
      assertNotNull(string0);
      assertEquals("@$kh%/0puJ*v8##", processingInstruction0.getTarget());
  }
}
