/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.crypto.hash;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import org.jsecurity.crypto.hash.Md2Hash;

public class Md2HashEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Md2Hash.getAlgorithmName()Ljava/lang/String;: root-Branch
   * 2 org.jsecurity.crypto.hash.Md2Hash.<init>(Ljava/lang/Object;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Md2Hash md2Hash0 = new Md2Hash((Object) "MD2");
      assertEquals("8eecf0d23d248b0e6223b8a10ddbf1e5", md2Hash0.toHex());
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Md2Hash.fromBase64String(Ljava/lang/String;)Lorg/jsecurity/crypto/hash/Md2Hash;: root-Branch
   * 2 org.jsecurity.crypto.hash.Md2Hash.<init>()V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      Md2Hash md2Hash0 = Md2Hash.fromBase64String("");
      assertEquals("", md2Hash0.toHex());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Md2Hash.fromHexString(Ljava/lang/String;)Lorg/jsecurity/crypto/hash/Md2Hash;: root-Branch
   * 2 org.jsecurity.crypto.hash.Md2Hash.<init>()V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try {
        Md2Hash.fromHexString("\u0005)\uFFFD\u0000j\uFFFD\uFFFD\uFFFD");
        fail("Expecting exception: IllegalArgumentException");
      } catch(IllegalArgumentException e) {
        /*
         * Illegal hexadecimal charcter \u0005 at index 0
         */
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jsecurity.crypto.hash.Md2Hash.<init>(Ljava/lang/Object;Ljava/lang/Object;I)V: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      Md2Hash md2Hash0 = new Md2Hash((Object) "juzw0j0kiw5iI7ihDdvx5Q==", (Object) "MD2", (-10));
      assertEquals("d4dd8349a17909dbfd8070e77dca8ca4", md2Hash0.toHex());
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * 1 org.jsecurity.crypto.hash.Md2Hash.<init>(Ljava/lang/Object;Ljava/lang/Object;)V: root-Branch
   * 2 org.jsecurity.crypto.hash.Md2Hash.getAlgorithmName()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Md2Hash md2Hash0 = new Md2Hash((Object) "MD2", (Object) "MD2");
      assertEquals("ab8e5ccdec47cc195d965629ca0d36f7", md2Hash0.toHex());
  }
}
