/*
 * This file was automatically generated by EvoSuite
 */

package com.sap.netweaver.porta.ide.eclipse.util;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import com.sap.netweaver.porta.ide.eclipse.util.SapNWServerUtil;

public class SapNWServerUtilEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 com.sap.netweaver.porta.ide.eclipse.util.SapNWServerUtil.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      SapNWServerUtil sapNWServerUtil0 = new SapNWServerUtil();
  }
}
