/*
 * This file was automatically generated by EvoSuite
 */

package messages.round;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import messages.round.PowerUpHitMsg;

@RunWith(EvoSuiteRunner.class)
public class PowerUpHitMsgEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 messages.round.PowerUpHitMsg.getType()I: root-Branch
   * 2 messages.round.PowerUpHitMsg.<init>(III)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      PowerUpHitMsg powerUpHitMsg0 = new PowerUpHitMsg(1883, 1883, 1883);
      int int0 = powerUpHitMsg0.getType();
      assertEquals(1883, powerUpHitMsg0.getPowerUpID());
      assertEquals(1883, int0);
      assertEquals(1883, powerUpHitMsg0.getPlayerID());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 messages.round.PowerUpHitMsg.getPowerUpID()I: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      PowerUpHitMsg powerUpHitMsg0 = new PowerUpHitMsg(1883, 1883, 1883);
      int int0 = powerUpHitMsg0.getPowerUpID();
      assertEquals(1883, powerUpHitMsg0.getType());
      assertEquals(1883, int0);
      assertEquals(1883, powerUpHitMsg0.getPlayerID());
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 messages.round.PowerUpHitMsg.getPlayerID()I: root-Branch
   * 2 messages.round.PowerUpHitMsg.<init>(III)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      PowerUpHitMsg powerUpHitMsg0 = new PowerUpHitMsg(1883, 1883, 1883);
      int int0 = powerUpHitMsg0.getPlayerID();
      assertEquals(1883, powerUpHitMsg0.getPowerUpID());
      assertEquals(1883, powerUpHitMsg0.getType());
      assertEquals(1883, int0);
  }
}
