/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authc;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import org.jsecurity.authc.AuthenticationInfo;
import org.jsecurity.authc.SimpleAccount;
import org.jsecurity.authc.SimpleAuthenticationInfo;
import org.jsecurity.authz.Permission;
import org.jsecurity.subject.PrincipalCollection;
import org.jsecurity.subject.SimplePrincipalCollection;

public class SimpleAuthenticationInfoEvoSuiteTest {


  //Test case number: 0
  /*
   * 9 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.getCredentials()Ljava/lang/Object;: root-Branch
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.getPrincipals()Lorg/jsecurity/subject/PrincipalCollection;: root-Branch
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.<init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)V: root-Branch
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I3 Branch 1 IFNULL L114 - false
   * 5 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I6 Branch 2 IFNULL L114 - false
   * 6 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I10 Branch 3 IFEQ L114 - true
   * 7 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I18 Branch 4 IFNONNULL L118 - true
   * 8 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I31 Branch 5 IFEQ L121 - false
   * 9 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I63 Branch 6 IFNONNULL L131 - false
   */
  @Test
  public void test0()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo((Object) "oR5d=x81=Cu*fF", (Object) null, "oR5d=x81=Cu*fF");
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAuthenticationInfo0);
  }

  //Test case number: 1
  /*
   * 7 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I23 Branch 12 IFNULL L168 - false
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I29 Branch 13 IFNE L168 - true
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.<init>(Lorg/jsecurity/subject/PrincipalCollection;Ljava/lang/Object;)V: root-Branch
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.setPrincipals(Lorg/jsecurity/subject/PrincipalCollection;)V: root-Branch
   * 5 org.jsecurity.authc.SimpleAuthenticationInfo.<init>()V: root-Branch
   * 6 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I4 Branch 10 IF_ACMPNE L163 - false
   * 7 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I11 Branch 11 IFNE L164 - true
   */
  @Test
  public void test1()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      simpleAuthenticationInfo0.setPrincipals((PrincipalCollection) simplePrincipalCollection0);
      List<Object> list0 = simplePrincipalCollection0.asList();
      SimpleAuthenticationInfo simpleAuthenticationInfo1 = new SimpleAuthenticationInfo((PrincipalCollection) simplePrincipalCollection0, (Object) list0);
      boolean boolean0 = simpleAuthenticationInfo0.equals((Object) simpleAuthenticationInfo1);
      assertEquals(true, boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I3 Branch 1 IFNULL L114 - true
   */
  @Test
  public void test2()  throws Throwable  {
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      HashSet<SimpleAuthenticationInfo> hashSet0 = new HashSet<SimpleAuthenticationInfo>();
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo((PrincipalCollection) simplePrincipalCollection0, (Object) hashSet0);
      simpleAuthenticationInfo0.merge((AuthenticationInfo) null);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I6 Branch 2 IFNULL L114 - true
   */
  @Test
  public void test3()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAuthenticationInfo0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I10 Branch 3 IFEQ L114 - false
   */
  @Test
  public void test4()  throws Throwable  {
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      HashSet<SimpleAuthenticationInfo> hashSet0 = new HashSet<SimpleAuthenticationInfo>();
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo((PrincipalCollection) simplePrincipalCollection0, (Object) hashSet0);
      TreeSet<Permission> treeSet0 = new TreeSet<Permission>();
      SimpleAccount simpleAccount0 = new SimpleAccount((PrincipalCollection) simplePrincipalCollection0, (Object) simplePrincipalCollection0, (Set<String>) null, (Set<Permission>) treeSet0);
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAccount0);
      assertEquals(true, hashSet0.isEmpty());
      assertEquals(0, hashSet0.size());
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I83 Branch 8 IFNE L140 - true
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I111 Branch 9 IFEQ L148 - true
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.setCredentials(Ljava/lang/Object;)V: root-Branch
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I18 Branch 4 IFNONNULL L118 - true
   * 5 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I31 Branch 5 IFEQ L121 - false
   * 6 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I70 Branch 7 IFNONNULL L135 - true
   * 7 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I83 Branch 8 IFNE L140 - false
   * 8 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I111 Branch 9 IFEQ L148 - false
   * 9 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I63 Branch 6 IFNONNULL L131 - true
   */
  @Test
  public void test5()  throws Throwable  {
      Object object0 = new Object();
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo(object0, object0, "");
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAuthenticationInfo0);
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAuthenticationInfo0);
  }

  //Test case number: 6
  /*
   * 4 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I4 Branch 10 IF_ACMPNE L163 - true
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I11 Branch 11 IFNE L164 - true
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I23 Branch 12 IFNULL L168 - true
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I34 Branch 14 IFNULL L168 - false
   */
  @Test
  public void test6()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      SimpleAuthenticationInfo simpleAuthenticationInfo1 = new SimpleAuthenticationInfo((Object) simplePrincipalCollection0, (Object) simpleAuthenticationInfo0, "");
      boolean boolean0 = simpleAuthenticationInfo0.equals((Object) simpleAuthenticationInfo1);
      assertEquals(false, boolean0);
      assertFalse(simpleAuthenticationInfo1.equals(simpleAuthenticationInfo0));
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I11 Branch 11 IFNE L164 - false
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.<init>(Lorg/jsecurity/subject/PrincipalCollection;Ljava/lang/Object;)V: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      HashSet<SimpleAuthenticationInfo> hashSet0 = new HashSet<SimpleAuthenticationInfo>();
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo((PrincipalCollection) simplePrincipalCollection0, (Object) hashSet0);
      boolean boolean0 = simpleAuthenticationInfo0.equals((Object) simplePrincipalCollection0);
      assertEquals(false, boolean0);
  }

  //Test case number: 8
  /*
   * 4 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I29 Branch 13 IFNE L168 - false
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.setPrincipals(Lorg/jsecurity/subject/PrincipalCollection;)V: root-Branch
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I4 Branch 10 IF_ACMPNE L163 - true
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I23 Branch 12 IFNULL L168 - false
   */
  @Test
  public void test8()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      SimplePrincipalCollection simplePrincipalCollection0 = new SimplePrincipalCollection();
      simpleAuthenticationInfo0.setPrincipals((PrincipalCollection) simplePrincipalCollection0);
      SimpleAuthenticationInfo simpleAuthenticationInfo1 = new SimpleAuthenticationInfo((Object) simplePrincipalCollection0, (Object) simpleAuthenticationInfo0, "`");
      boolean boolean0 = simpleAuthenticationInfo0.equals((Object) simpleAuthenticationInfo1);
      assertEquals(false, boolean0);
  }

  //Test case number: 9
  /*
   * 4 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I34 Branch 14 IFNULL L168 - true
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I4 Branch 10 IF_ACMPNE L163 - false
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I11 Branch 11 IFNE L164 - true
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.equals(Ljava/lang/Object;)Z: I23 Branch 12 IFNULL L168 - true
   */
  @Test
  public void test9()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      SimpleAuthenticationInfo simpleAuthenticationInfo1 = new SimpleAuthenticationInfo();
      boolean boolean0 = simpleAuthenticationInfo1.equals((Object) simpleAuthenticationInfo0);
      assertEquals(true, boolean0);
  }

  //Test case number: 10
  /*
   * 13 covered goals:
   * 1 org.jsecurity.authc.SimpleAuthenticationInfo.hashCode()I: I4 Branch 15 IFNULL L178 - false
   * 2 org.jsecurity.authc.SimpleAuthenticationInfo.getCredentials()Ljava/lang/Object;: root-Branch
   * 3 org.jsecurity.authc.SimpleAuthenticationInfo.getPrincipals()Lorg/jsecurity/subject/PrincipalCollection;: root-Branch
   * 4 org.jsecurity.authc.SimpleAuthenticationInfo.toString()Ljava/lang/String;: root-Branch
   * 5 org.jsecurity.authc.SimpleAuthenticationInfo.<init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)V: root-Branch
   * 6 org.jsecurity.authc.SimpleAuthenticationInfo.<init>()V: root-Branch
   * 7 org.jsecurity.authc.SimpleAuthenticationInfo.hashCode()I: I4 Branch 15 IFNULL L178 - true
   * 8 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I3 Branch 1 IFNULL L114 - false
   * 9 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I6 Branch 2 IFNULL L114 - false
   * 10 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I10 Branch 3 IFEQ L114 - true
   * 11 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I18 Branch 4 IFNONNULL L118 - false
   * 12 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I63 Branch 6 IFNONNULL L131 - true
   * 13 org.jsecurity.authc.SimpleAuthenticationInfo.merge(Lorg/jsecurity/authc/AuthenticationInfo;)V: I70 Branch 7 IFNONNULL L135 - false
   */
  @Test
  public void test10()  throws Throwable  {
      SimpleAuthenticationInfo simpleAuthenticationInfo0 = new SimpleAuthenticationInfo();
      HashSet<Object> hashSet0 = new HashSet<Object>();
      SimpleAuthenticationInfo simpleAuthenticationInfo1 = new SimpleAuthenticationInfo((Object) simpleAuthenticationInfo0, (Object) hashSet0, "2");
      assertNotNull(simpleAuthenticationInfo1);
      
      simpleAuthenticationInfo0.merge((AuthenticationInfo) simpleAuthenticationInfo1);
      // Undeclared exception!
      try {
        simpleAuthenticationInfo0.toString();
        fail("Expecting exception: StackOverflowError");
      } catch(StackOverflowError e) {
      }
  }
}
