/*
 * This file was automatically generated by EvoSuite
 */

package org.jsecurity.authc;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.net.Inet4Address;
import java.net.InetAddress;
import org.jsecurity.authc.UsernamePasswordToken;

public class UsernamePasswordTokenEvoSuiteTest {


  //Test case number: 0
  /*
   * 3 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.getPrincipal()Ljava/lang/Object;: root-Branch
   * 2 org.jsecurity.authc.UsernamePasswordToken.<init>(Ljava/lang/String;[CZLjava/net/InetAddress;)V: root-Branch
   * 3 org.jsecurity.authc.UsernamePasswordToken.getUsername()Ljava/lang/String;: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("", "");
      String string0 = (String)usernamePasswordToken0.getPrincipal();
      assertNotNull(string0);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - , rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.<init>(Ljava/lang/String;[CZ)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      char[] charArray0 = new char[1];
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("XC^Fjp[", charArray0, false);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - XC^Fjp[, rememberMe=false", usernamePasswordToken0.toString());
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.<init>(Ljava/lang/String;[CLjava/net/InetAddress;)V: root-Branch
   */
  @Test
  public void test2()  throws Throwable  {
      char[] charArray0 = new char[7];
      Inet4Address inet4Address0 = (Inet4Address)InetAddress.getLoopbackAddress();
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken((String) null, charArray0, (InetAddress) inet4Address0);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false (localhost/127.0.0.1)", usernamePasswordToken0.toString());
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.isRememberMe()Z: root-Branch
   */
  @Test
  public void test3()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("(.`dK(", "");
      boolean boolean0 = usernamePasswordToken0.isRememberMe();
      assertEquals(false, boolean0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.setRememberMe(Z)V: root-Branch
   */
  @Test
  public void test4()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)InetAddress.getLoopbackAddress();
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("Hp`O", "Hp`O", true, (InetAddress) inet4Address0);
      usernamePasswordToken0.setRememberMe(true);
      assertEquals(true, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 5
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.getPassword()[C: root-Branch
   * 2 org.jsecurity.authc.UsernamePasswordToken.getCredentials()Ljava/lang/Object;: root-Branch
   */
  @Test
  public void test5()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)InetAddress.getLoopbackAddress();
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("Hp`O", "Hp`O", true, (InetAddress) inet4Address0);
      Object object0 = usernamePasswordToken0.getCredentials();
      assertEquals(true, usernamePasswordToken0.isRememberMe());
      assertNotNull(object0);
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.setUsername(Ljava/lang/String;)V: root-Branch
   */
  @Test
  public void test6()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("(.`dK(", "");
      usernamePasswordToken0.setUsername("XC^Fjp[");
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - XC^Fjp[, rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.getInetAddress()Ljava/net/InetAddress;: root-Branch
   */
  @Test
  public void test7()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("(.`dK(", "");
      usernamePasswordToken0.getInetAddress();
      assertEquals(false, usernamePasswordToken0.isRememberMe());
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - (.`dK(, rememberMe=false", usernamePasswordToken0.toString());
  }

  //Test case number: 8
  /*
   * 5 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.clear()V: I29 Branch 6 IF_ICMPGE L341 - false
   * 2 org.jsecurity.authc.UsernamePasswordToken.setPassword([C)V: root-Branch
   * 3 org.jsecurity.authc.UsernamePasswordToken.<init>()V: root-Branch
   * 4 org.jsecurity.authc.UsernamePasswordToken.clear()V: I19 Branch 5 IFNULL L340 - false
   * 5 org.jsecurity.authc.UsernamePasswordToken.clear()V: I29 Branch 6 IF_ICMPGE L341 - true
   */
  @Test
  public void test8()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken();
      char[] charArray0 = new char[4];
      usernamePasswordToken0.setPassword(charArray0);
      usernamePasswordToken0.clear();
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.setInetAddress(Ljava/net/InetAddress;)V: root-Branch
   */
  @Test
  public void test9()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("(.`dK(", "");
      usernamePasswordToken0.setInetAddress((InetAddress) null);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - (.`dK(, rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.<init>(Ljava/lang/String;[C)V: root-Branch
   */
  @Test
  public void test10()  throws Throwable  {
      char[] charArray0 = new char[4];
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken((String) null, charArray0);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false", usernamePasswordToken0.toString());
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * 1 org.jsecurity.authc.UsernamePasswordToken.clear()V: I19 Branch 5 IFNULL L340 - true
   */
  @Test
  public void test11()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken((String) null, (String) null);
      usernamePasswordToken0.clear();
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 12
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.clear()V: I19 Branch 5 IFNULL L340 - false
   * 2 org.jsecurity.authc.UsernamePasswordToken.clear()V: I29 Branch 6 IF_ICMPGE L341 - true
   */
  @Test
  public void test12()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken("(.`dK(", "");
      usernamePasswordToken0.clear();
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false", usernamePasswordToken0.toString());
      assertEquals(false, usernamePasswordToken0.isRememberMe());
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.toString()Ljava/lang/String;: I40 Branch 7 IFNULL L363 - true
   * 2 org.jsecurity.authc.UsernamePasswordToken.<init>()V: root-Branch
   */
  @Test
  public void test13()  throws Throwable  {
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken();
      String string0 = usernamePasswordToken0.toString();
      assertNotNull(string0);
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=false", string0);
  }

  //Test case number: 14
  /*
   * 2 covered goals:
   * 1 org.jsecurity.authc.UsernamePasswordToken.toString()Ljava/lang/String;: I40 Branch 7 IFNULL L363 - false
   * 2 org.jsecurity.authc.UsernamePasswordToken.<init>(Ljava/lang/String;[CZLjava/net/InetAddress;)V: root-Branch
   */
  @Test
  public void test14()  throws Throwable  {
      Inet4Address inet4Address0 = (Inet4Address)InetAddress.getLoopbackAddress();
      UsernamePasswordToken usernamePasswordToken0 = new UsernamePasswordToken((String) null, (String) null, true, (InetAddress) inet4Address0);
      String string0 = usernamePasswordToken0.toString();
      assertEquals("org.jsecurity.authc.UsernamePasswordToken - null, rememberMe=true (localhost/127.0.0.1)", string0);
      assertNotNull(string0);
      assertEquals(true, usernamePasswordToken0.isRememberMe());
  }
}
