/*
 * This file was automatically generated by EvoSuite
 */

package bierse.view;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import bierse.view.DefaultInfoViewMouseListener;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

public class DefaultInfoViewMouseListenerEvoSuiteTest {


  //Test case number: 0
  /*
   * 2 covered goals:
   * 1 bierse.view.DefaultInfoViewMouseListener.mouseEntered(Ljava/awt/event/MouseEvent;)V: root-Branch
   * 2 bierse.view.DefaultInfoViewMouseListener.<init>(Ljavax/swing/JFrame;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseEntered((MouseEvent) null);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * 1 bierse.view.DefaultInfoViewMouseListener.mouseMoved(Ljava/awt/event/MouseEvent;)V: root-Branch
   * 2 bierse.view.DefaultInfoViewMouseListener.<init>(Ljavax/swing/JFrame;)V: root-Branch
   */
  @Test
  public void test1()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseMoved((MouseEvent) null);
  }
}
