/*
 * This file was automatically generated by EvoSuite
 */

package client.view;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import client.view.GfxFactory;
import client.view.TileView;
import common.GameObject;
import common.Tile;
import java.awt.Point;

@RunWith(EvoSuiteRunner.class)
public class TileViewEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 client.view.TileView.<init>(Lcommon/GameObject;Lclient/view/GfxFactory;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      Tile tile0 = new Tile((Point) null);
      TileView tileView0 = null;
      try {
        tileView0 = new TileView((GameObject) tile0, (GfxFactory) null);
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
        /*
         * org/apache/log4j/Logger
         */
      }
  }
}
