/*
 * This file was automatically generated by EvoSuite
 */

package db;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import db.HighscoreTest;

@RunWith(EvoSuiteRunner.class)
public class HighscoreTestEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 db.HighscoreTest.<init>()V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      HighscoreTest highscoreTest0 = new HighscoreTest();
  }
}
